/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Spring.boot.api.example;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
